apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-demo
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node
            operator: NotIn
            values:
            - affinity
  containers:
  - name: node-anti-affinity
    image: nginx
    imagePullPolicy: Always